# SPDX-License-Identifier: GPL-2.0-or-later
#
# GENERATED by tools/generate_qmk_settings.py — do not edit by hand.
#
# Derived from vial-gui (https://github.com/vial-kb/vial-gui), GPL-2.0-or-later,
# which in turn mirrors vial-qmk's own settings description. Redistributed here
# under GPL-3.0-or-later as the "or later" option permits. See NOTICE.
"""The QMK settings schema: which QSIDs exist, how wide they are, and what they mean."""

from __future__ import annotations

#: Tabs, in order, each a list of fields. A field is either a boolean occupying one
#: bit of its QSID, or an integer occupying the whole of it.
TABS = (
    ('Magic', (
        {"type": 'boolean', "title": 'Swap Caps Lock and Left Control', "qsid": 21, "width": 4, "bit": 0},
        {"type": 'boolean', "title": 'Treat Caps Lock as Control', "qsid": 21, "width": 4, "bit": 1},
        {"type": 'boolean', "title": 'Swap Left Alt and GUI', "qsid": 21, "width": 4, "bit": 2},
        {"type": 'boolean', "title": 'Swap Right Alt and GUI', "qsid": 21, "width": 4, "bit": 3},
        {"type": 'boolean', "title": 'Disable the GUI keys', "qsid": 21, "width": 4, "bit": 4},
        {"type": 'boolean', "title": 'Swap ` and Escape', "qsid": 21, "width": 4, "bit": 5},
        {"type": 'boolean', "title": 'Swap \\ and Backspace', "qsid": 21, "width": 4, "bit": 6},
        {"type": 'boolean', "title": 'Enable N-key rollover', "qsid": 21, "width": 4, "bit": 7},
        {"type": 'boolean', "title": 'Swap Left Control and GUI', "qsid": 21, "width": 4, "bit": 8},
        {"type": 'boolean', "title": 'Swap Right Control and GUI', "qsid": 21, "width": 4, "bit": 9},
    )),
    ('Grave Escape', (
        {"type": 'boolean', "title": 'Always send Escape if Alt is pressed', "qsid": 1, "bit": 0},
        {"type": 'boolean', "title": 'Always send Escape if Control is pressed', "qsid": 1, "bit": 1},
        {"type": 'boolean', "title": 'Always send Escape if GUI is pressed', "qsid": 1, "bit": 2},
        {"type": 'boolean', "title": 'Always send Escape if Shift is pressed', "qsid": 1, "bit": 3},
    )),
    ('Tap-Hold', (
        {"type": 'integer', "title": 'Tapping Term', "qsid": 7, "width": 2, "min": 0, "max": 10000},
        {"type": 'boolean', "title": 'Permissive Hold', "qsid": 8, "bit": 0},
        {"type": 'boolean', "title": 'Ignore Mod Tap Interrupt', "qsid": 8, "bit": 1},
        {"type": 'boolean', "title": 'Tapping Force Hold', "qsid": 8, "bit": 2},
        {"type": 'boolean', "title": 'Retro Tapping', "qsid": 8, "bit": 3},
        {"type": 'boolean', "title": 'Permissive Hold', "qsid": 22},
        {"type": 'boolean', "title": 'Hold On Other Key Press', "qsid": 23},
        {"type": 'boolean', "title": 'Retro Tapping', "qsid": 24},
        {"type": 'integer', "title": 'Quick Tap Term', "qsid": 25, "width": 2, "min": 0, "max": 10000},
        {"type": 'integer', "title": 'Tap Code Delay', "qsid": 18, "width": 2, "min": 0, "max": 1000},
        {"type": 'integer', "title": 'Tap Hold Caps Delay', "qsid": 19, "width": 2, "min": 0, "max": 1000},
        {"type": 'integer', "title": 'Tapping Toggle', "qsid": 20, "width": 1, "min": 0, "max": 100},
        {"type": 'boolean', "title": 'Chordal Hold', "qsid": 26},
        {"type": 'integer', "title": 'Flow Tap', "qsid": 27, "width": 2, "min": 0, "max": 10000},
    )),
    ('Auto Shift', (
        {"type": 'boolean', "title": 'Enable', "qsid": 3, "bit": 0},
        {"type": 'boolean', "title": 'Enable for modifiers', "qsid": 3, "bit": 1},
        {"type": 'integer', "title": 'Timeout', "qsid": 4, "width": 2, "min": 0, "max": 1000},
        {"type": 'boolean', "title": 'Do not Auto Shift special keys', "qsid": 3, "bit": 2},
        {"type": 'boolean', "title": 'Do not Auto Shift numeric keys', "qsid": 3, "bit": 3},
        {"type": 'boolean', "title": 'Do not Auto Shift alpha characters', "qsid": 3, "bit": 4},
        {"type": 'boolean', "title": 'Enable keyrepeat', "qsid": 3, "bit": 5},
        {"type": 'boolean', "title": 'Disable keyrepeat when timeout is exceeded', "qsid": 3, "bit": 6},
    )),
    ('Combo', (
        {"type": 'integer', "title": 'Time out period for combos', "qsid": 2, "width": 2, "min": 0, "max": 10000},
    )),
    ('One Shot Keys', (
        {"type": 'integer', "title": 'Tapping this number of times holds the key until tapped once again', "qsid": 5, "width": 1, "min": 0, "max": 50},
        {"type": 'integer', "title": 'Time (in ms) before the one shot key is released', "qsid": 6, "width": 2, "min": 0, "max": 60000},
    )),
    ('Mouse keys', (
        {"type": 'integer', "title": 'Delay between pressing a movement key and cursor movement', "qsid": 9, "width": 2, "min": 0, "max": 10000},
        {"type": 'integer', "title": 'Time between cursor movements in milliseconds', "qsid": 10, "width": 2, "min": 0, "max": 10000},
        {"type": 'integer', "title": 'Step size', "qsid": 11, "width": 2, "min": 0, "max": 1000},
        {"type": 'integer', "title": 'Maximum cursor speed at which acceleration stops', "qsid": 12, "width": 2, "min": 0, "max": 1000},
        {"type": 'integer', "title": 'Time until maximum cursor speed is reached', "qsid": 13, "width": 2, "min": 0, "max": 1000},
        {"type": 'integer', "title": 'Delay between pressing a wheel key and wheel movement', "qsid": 14, "width": 2, "min": 0, "max": 10000},
        {"type": 'integer', "title": 'Time between wheel movements', "qsid": 15, "width": 2, "min": 0, "max": 10000},
        {"type": 'integer', "title": 'Maximum number of scroll steps per scroll action', "qsid": 16, "width": 2, "min": 0, "max": 1000},
        {"type": 'integer', "title": 'Time until maximum scroll speed is reached', "qsid": 17, "width": 2, "min": 0, "max": 1000},
    )),
)

#: Bytes each QSID occupies. Absent means one.
WIDTHS = {
    1: 1,
    2: 2,
    3: 1,
    4: 2,
    5: 1,
    6: 2,
    7: 2,
    8: 1,
    9: 2,
    10: 2,
    11: 2,
    12: 2,
    13: 2,
    14: 2,
    15: 2,
    16: 2,
    17: 2,
    18: 2,
    19: 2,
    20: 1,
    21: 4,
    22: 1,
    23: 1,
    24: 1,
    25: 2,
    26: 1,
    27: 2,
}

