#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 白い熊
"""Regenerate ``svalboard/protocol/qmk_settings_table.py`` from a vial-gui checkout.

The schema says which QSID each setting lives in, how many bytes that QSID occupies
and which bit within it a boolean uses. Getting a width wrong writes the wrong number
of bytes to the keyboard, so it is generated rather than transcribed.

Usage::

    git clone --depth 1 https://github.com/vial-kb/vial-gui.git /tmp/vial-gui
    tools/generate_qmk_settings.py /tmp/vial-gui
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HEADER = '''# SPDX-License-Identifier: GPL-2.0-or-later
#
# GENERATED by tools/generate_qmk_settings.py — do not edit by hand.
#
# Derived from vial-gui (https://github.com/vial-kb/vial-gui), GPL-2.0-or-later,
# which in turn mirrors vial-qmk's own settings description. Redistributed here
# under GPL-3.0-or-later as the "or later" option permits. See NOTICE.
"""The QMK settings schema: which QSIDs exist, how wide they are, and what they mean."""

from __future__ import annotations

#: Tabs, in order, each a list of fields. A field is either a boolean occupying one
#: bit of its QSID, or an integer occupying the whole of it.
TABS = (
'''


def generate(root: Path, destination: Path) -> None:
    source = root / "src" / "main" / "resources" / "base" / "qmk_settings.json"
    if not source.exists():
        raise SystemExit(f"{source} not found; is that a vial-gui checkout?")
    document = json.loads(source.read_text(encoding="utf-8"))
    tabs = document["tabs"] if isinstance(document, dict) else document

    lines = [HEADER]
    fields = 0
    widths: dict[int, int] = {}
    for tab in tabs:
        lines.append(f"    ({tab['name']!r}, (")
        for field in tab.get("fields", []):
            fields += 1
            widths.setdefault(field["qsid"], field.get("width", 1))
            parts = [
                f'"type": {field["type"]!r}',
                f'"title": {field["title"]!r}',
                f'"qsid": {field["qsid"]}',
            ]
            for name in ("width", "bit", "min", "max"):
                if name in field:
                    parts.append(f'"{name}": {field[name]}')
            lines.append("        {" + ", ".join(parts) + "},")
        lines.append("    )),")
    lines.append(")")
    lines.append("")
    lines.append("#: Bytes each QSID occupies. Absent means one.")
    lines.append("WIDTHS = {")
    for qsid in sorted(widths):
        lines.append(f"    {qsid}: {widths[qsid]},")
    lines.append("}")
    lines.append("")

    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{destination}: {len(tabs)} tabs, {fields} fields, {len(widths)} QSIDs")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("vial_gui", type=Path, help="path to a vial-gui checkout")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent
        / "svalboard"
        / "protocol"
        / "qmk_settings_table.py",
    )
    args = parser.parse_args(argv)
    generate(args.vial_gui.resolve(), args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
