#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 白い熊
"""Regenerate ``svalboard/protocol/keycodes/table.py`` from a vial-gui checkout.

QMK's keycode numbering is not something to reproduce from memory: a single wrong
value silently writes the wrong key to the keyboard. So the table is generated from
vial-gui (GPL-2.0-or-later), which tracks it against the firmware, and the generated
file is committed so the build needs no network and no submodule.

Usage::

    git clone --depth 1 https://github.com/vial-kb/vial-gui.git /tmp/vial-gui
    tools/generate_keycodes.py /tmp/vial-gui

Re-run it when vial-qmk gains keycodes, and commit the diff.
"""

from __future__ import annotations

import argparse
import sys
import types
from pathlib import Path

HEADER = '''\
# SPDX-License-Identifier: GPL-2.0-or-later
#
# GENERATED by tools/generate_keycodes.py — do not edit by hand.
#
# Derived from vial-gui (https://github.com/vial-kb/vial-gui), which is
# GPL-2.0-or-later, from commit {commit}. Redistributed here under GPL-3.0-or-later
# as the "or later" option permits. See NOTICE.
#
# Vial protocol {protocol} numbering.
"""QMK keycode numbering, names, labels and picker categories."""

from __future__ import annotations

'''


def _load_vial_gui(root: Path):
    python_root = root / "src" / "main" / "python"
    if not (python_root / "keycodes" / "keycodes.py").exists():
        raise SystemExit(f"{root} does not look like a vial-gui checkout.")
    sys.path.insert(0, str(python_root))

    # keycodes.py calls recreate_keycodes() at import time, which resolves every
    # identifier — including the ones only vial-gui's expression evaluator can parse,
    # such as TD(0) and M0. That evaluator needs simpleeval, a dependency this
    # generator would otherwise not have. The identifiers it fails on land only in
    # vial-gui's RAWCODES_MAP, which nothing here reads, so a stub that declines to
    # parse is both sufficient and honest about what is being skipped.
    stub = types.ModuleType("any_keycode")

    class _Unparsed(Exception):
        pass

    class AnyKeycode:  # noqa: N801  (mirrors the name being stubbed)
        def decode(self, _value: str) -> int:
            raise _Unparsed("Not resolved by the generator; see tools/generate_keycodes.py.")

    stub.AnyKeycode = AnyKeycode  # type: ignore[attr-defined]
    sys.modules.setdefault("any_keycode", stub)

    import keycodes.keycodes as kc  # noqa: PLC0415  (path must be set first)

    kc.Keycode.protocol = 6
    return kc


def _commit(root: Path) -> str:
    import subprocess

    try:
        out = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except Exception:
        return "unknown"


#: Picker tabs, in the order they should appear. Maps our tab name to the vial-gui
#: list that supplies it. The Svalboard-specific and per-keyboard tabs (macros, tap
#: dances, layers, custom keycodes) are generated at runtime from the connected
#: board, so they are deliberately absent here.
CATEGORY_SOURCES = [
    ("special", "KEYCODES_SPECIAL"),
    ("basic", "KEYCODES_BASIC"),
    ("shifted", "KEYCODES_SHIFTED"),
    ("iso", "KEYCODES_ISO"),
    ("modifiers", "KEYCODES_MODIFIERS"),
    ("quantum", "KEYCODES_QUANTUM"),
    ("backlight", "KEYCODES_BACKLIGHT"),
    ("media", "KEYCODES_MEDIA"),
    ("midi", "KEYCODES_MIDI_BASIC"),
    ("midi_advanced", "KEYCODES_MIDI_ADVANCED"),
    ("boot", "KEYCODES_BOOT"),
]


def generate(root: Path, destination: Path) -> None:
    kc = _load_vial_gui(root)
    table = dict(sorted(kc.keycodes_v6.kc.items()))
    masked = sorted(kc.keycodes_v6.masked)

    labels: dict[str, str] = {}
    tooltips: dict[str, str] = {}
    aliases: dict[str, str] = {}
    described = [
        keycode
        for _, attribute in CATEGORY_SOURCES
        for keycode in getattr(kc, attribute, ())
    ]
    for keycode in described:
        qmk_id = keycode.qmk_id
        if keycode.label and keycode.label != qmk_id:
            labels[qmk_id] = keycode.label
        if keycode.tooltip:
            tooltips[qmk_id] = keycode.tooltip
        for alias in keycode.alias:
            if alias != qmk_id:
                aliases[alias] = qmk_id

    categories: dict[str, list[str]] = {}
    for name, attribute in CATEGORY_SOURCES:
        entries = getattr(kc, attribute, None)
        if entries:
            categories[name] = [entry.qmk_id for entry in entries]

    def emit(handle, name: str, mapping: dict[str, object]) -> None:
        handle.write(f"{name} = {{\n")
        for key, value in mapping.items():
            rendered = f"0x{value:04X}" if isinstance(value, int) else repr(value)
            handle.write(f"    {key!r}: {rendered},\n")
        handle.write("}\n\n")

    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8") as handle:
        handle.write(HEADER.format(commit=_commit(root), protocol=6))
        handle.write("#: Every QMK identifier the firmware understands, mapped to its value.\n")
        emit(handle, "KEYCODES", table)

        handle.write(
            "#: Outer prefixes that compose with a basic keycode, e.g. 0x0100 -> LCTL(kc).\n"
            "#: A code whose high byte is one of these is a composite, not a keycode in\n"
            "#: its own right, and must be split before it is named.\n"
        )
        handle.write("MASKED = frozenset({\n")
        for prefix in masked:
            handle.write(f"    0x{prefix:04X},\n")
        handle.write("})\n\n")

        handle.write("#: Short label shown on a key. Newlines are intentional line breaks.\n")
        emit(handle, "LABELS", dict(sorted(labels.items())))

        handle.write("#: Longer description, shown on hover.\n")
        emit(handle, "TOOLTIPS", dict(sorted(tooltips.items())))

        handle.write("#: Accepted spellings, mapped to the canonical identifier.\n")
        emit(handle, "ALIASES", dict(sorted(aliases.items())))

        handle.write("#: Picker tabs. Runtime tabs are built from the connected keyboard.\n")
        handle.write("CATEGORIES = {\n")
        for name, entries in categories.items():
            handle.write(f"    {name!r}: (\n")
            for entry in entries:
                handle.write(f"        {entry!r},\n")
            handle.write("    ),\n")
        handle.write("}\n")

    print(
        f"{destination}: {len(table)} keycodes, {len(masked)} masked prefixes, "
        f"{len(labels)} labels, {len(aliases)} aliases, "
        f"{len(categories)} categories"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("vial_gui", type=Path, help="path to a vial-gui checkout")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent
        / "svalboard"
        / "protocol"
        / "keycodes"
        / "table.py",
    )
    args = parser.parse_args(argv)
    generate(args.vial_gui.resolve(), args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
